name: zxcvbn
version: 1.0.0
description: Dart port of DropBox's zxcvbn library.
homepage: https://github.com/HannesGitH/zxcvbn-dart-localizable
repository: https://github.com/HannesGitH/zxcvbn-dart-localizable

dev_dependencies:
  test: any
environment:
  sdk: '>=2.12.0 <3.0.0'
